[package]
name = "d_logger"
version = "0.1.0"
edition = "2024"
description="A simple logger"
license="MIT"
repository=""
readme = "readme.md"
keywords = ["log", "logger"]
categories = ["filesystem"]

[dependencies]
chrono = "0.4.40"
regex = "1.11.1"
